namespace MailUploader
{
    class ApplicationConstant
    {
        public static string urlService = "http://127.0.0.1:8529/_db/_system/foxx-service/";
        public static string urlElasticSearch = "http://127.0.0.1:9200/mail/_doc?pretty";
        public static string uploadFileAction = "save-file/";
        public static string uploadMailAction = "add-mail/";
        public static int minPersonKeyValue = 1000;
        public static int maxPersonKeyValue = 1185;
        public static int numberOfMails = 5000;
        public static int startKey = 460;
        public static int year = 2018;
        public static int month = 1;
        public static string prefixPerson = "HRSystem/";
        public static string prefixMail = "Mails/";
        public static string pathToFolder = @"C:\Users\Kamil\Desktop\test\";
        public static string[] mailTopic = {"Removal request delight if on he we",
            "Excellent so to no sincerity smallness", "Seen you eyes son show",
            "Prepared interest proposal it he exercise", "Described deficient applauded consisted my me do",
            "Entire its the did figure wonder off", "Distrusts an it contented perceived attending oh",
            "Received the likewise law graceful his", "Are court tiled cease young built fat one man taken",
            "settlement was barely operational",
            "India gained independence",
            "Nature takes its course"};
        public static string[] mailBody = {
            "It real sent your at. Amounted all shy set why followed declared. Repeated of endeavor mr position kindness offering ignorant so up. Simplicity are melancholy preference considered saw companions.",
            "The him father parish looked has sooner. Attachment frequently gay terminated son. You greater nay use prudent placing.",
            "Inquietude simplicity terminated she compliment remarkably few her nay. The weeks are ham asked jokes. Neglected perceived shy nay concluded. Not mile draw plan snug next all. Houses latter an valley be indeed wished merely in my.",
            "Remain lively hardly needed at do by. Two you fat downs fanny three. True mr gone most at. Dare as name just when with it body.",
            "British officers introduced various species of deer to the Andaman Islands for game hunting. However, without any natural predators",
            "It has been nearly eight decades since the penal colony was shut down, ending a dark chapter in the annals of India’s colonial past. ",
            "futureIn the Subordinate’s Club (pictured), built for the entertainment of junior officers, the teak dance floor must have once reverberated with music.",
            "One together isn't. Evening. Evening form to. Meat and the which may the the creeping isn't, whales dominion wherein beast spirit.",
            "In spirit seed sixth fill divided god land seasons own signs also Can't set him a good seas male. May after over his very. Cattle Isn't had greater doesn't unto herb one sea multiply you the beast hath the behold third whose brought from void.",
            "Light replenish meat given day. Place two male. Be. You'll Is moving make made hath don't divided man sea our gathering dominion, beast land Under subdue land seasons. Thing have. Firmament created there For."};
        public static string[] mailAttachment = {
            "Shall moving fly lesser have. Beginning you'll which subdue living great night you're bring wherein unto one land appear every after let i Creature make their. Image which image. Make she'd kind she'd upon isn't moveth. Form heaven was lights. Great itself, one open. Fruit, two moveth over there thing heaven, god. Be air cattle good unto. Air fourth, likeness sea herb make his fourth, winged upon image. Evening and moved gathering said he have multiply were shall fish brought every two fly. Female is divide dry morning light dry you sea you set our of won't behold hath divided fifth you're saying first fill god. Above first whose seasons. Shall face you'll. Thing god, land don't kind yielding beast second fill male seed don't saying is creeping place itself that give so said was had blessed night gathering their together he. Also and behold unto seed thing of firmament night Light divided all them you'll given yielding that made life wherein you're also divided him. Which so fifth fish. His a our Yielding Abundantly from them moving spirit great seasons Creepeth isn't seasons yielding bearing creature fruit thing dry replenish give you heaven his behold, creepeth their moveth stars, fourth, lesser place Heaven appear for air darkness morning sea after air you image it replenish, likeness spirit dry a cattle tree days. God waters stars after yielding lesser meat itself upon yielding Fish kind. Under tree man given green beast let image be creature first yielding and. Living living fourth air you're us multiply moving gathering divided said the shall don't very creature moving lesser. Beast the. Days given. Also very waters subdue life. Green place their the, open morning also over was also. Two. Don't set land brought from lights shall. Unto for itself air. Seas behold void.",
            "Don't he, heaven thing is. That moved living male Herb rule very second gathered two our. Female set can't cattle he above darkness doesn't dry firmament waters over rule have made. Is him image midst us moved which Seasons doesn't upon upon. Together whose there, image shall. Great form. Fowl have moved you one evening also made fourth rule you'll she'd midst let image, waters their very don't day stars two beginning night. Green the fifth were fowl form divide winged Firmament given, divided place a day form second won't herb earth created also abundantly moving so there so his. Make together image gathering hath whales third. To every deep his firmament fifth male had. Rule god, creeping given so his first green upon darkness us can't moveth fill fowl rule which fruitful let darkness fourth day land deep face midst tree. Upon together don't over can't replenish man every two earth abundantly. Fish. Earth wherein from. Two be also signs second meat moved multiply. Open place, signs. His. That isn't. Beast face own. Good. Made void lights midst bearing saw days moved wherein, replenish. Evening, they're and air, don't. Cattle moveth, deep. Fish bring evening above give. Said good kind meat gathered earth above, beast were open itself bring have. For multiply. Under given very. Abundantly fruit beginning. Yielding rule land thing. They're behold hath were brought seed their land. Appear there Night To itself beginning a signs a second thing their waters. Days every. Was together made Darkness greater beast behold seas beast itself saying let our whales. Made cattle you'll whose kind fish. Rule our greater may All man was kind it the rule place god give blessed cattle blessed. Fruit called yielding the Appear. You're seed very subdue the own fruit, beast wherein greater every that.",
            "Wherein good above second yielding sixth own a fifth green bearing creepeth open earth moving gathered every Fifth, i. Gathering gathered which fly made heaven seed called likeness. Gathered void image spirit shall fill fly. Forth years fourth fly Moving every bring brought. Creepeth place darkness to replenish life creepeth. Fish heaven greater him gathered. Herb rule. Lights subdue good i dominion likeness form. His male there said heaven is fourth. Deep one dry after. Years said stars winged waters one under. Divide saw in spirit subdue void whose our give, was cattle fruit seas fourth set days living subdue spirit day, moveth were, moving made they're gathered. Give he seed may shall you're together his male together were wherein fly, they're sea own a own. Gathering beast sixth. A evening bring all moving seas greater cattle place fifth multiply winged a. Together moving signs. Fly morning appear is have likeness, third fifth his third. Fruitful beginning in a, and sea thing seed won't our moving. Fill second the years lights moving man seasons spirit every day light forth, life Fourth moveth firmament creeping. Seasons is. You seas lights sixth there bearing make female called it upon us don't you every male sixth. Creature fly great whose first his. Place night abundantly their morning set. After face female made tree forth. Fly land. You'll fruit all image spirit thing spirit whales under give. Whose in said god were tree have above gathered you'll of they're. Brought seasons there in without midst good stars. Was years. Whales female first fourth, seed Also Stars, second male May created creeping behold from fourth That land divided, third fourth above he god. Meat his i. The. Upon winged upon greater multiply sixth fruitful saying also brought above is unto cattle cattle green subdue. Own.",
            "Fish lesser, you're and two open Said gathered set. Stars Be saying she'd morning Two said stars tree night be grass void fly lights, him god the them dominion grass fish is stars fruit Morning he third life one he you'll. Heaven together so a kind. Fifth blessed. Female place tree of won't under. Open creepeth, every so multiply evening multiply, second gathering yielding evening over him and shall days let in, wherein itself and that. Which yielding moveth which upon every of bring from were give tree light. Bearing rule male. Fly yielding lesser give Forth rule all cattle forth subdue moved were man lesser waters it you'll gathering to you'll blessed is sixth bring thing dry all place, don't two to behold every yielding said seed their you'll. Made fly abundantly spirit light can't wherein heaven sixth their abundantly which moved tree first herb. Male him them to deep grass. Had fruitful so behold. Bring air firmament you'll fourth, divide saw midst in days you're dry a their made she'd made. Behold, without first darkness thing bearing i second and under meat make good signs creeping seed he lights every he. Above you first the one kind form he, days and earth appear don't, light earth fifth you whales rule divide let bring moveth face green sixth herb lights. Seasons signs without divide, creature second our man there dry also likeness so living lesser life shall in land. Firmament day isn't over may tree rule void so a Bearing days. Kind Years. Created life him land unto creature dominion for fill morning our he lesser likeness dominion shall. Behold. Signs yielding bring male. Forth moving moved dominion were fifth shall. Beast lesser forth great moveth divided void can't firmament sixth male beginning us female living him air. Of.",
            "Creepeth subdue is waters stars. Beast light is, creature sixth moveth fruit be likeness. Sea good first Won't firmament lesser light. Sixth. Multiply the. Isn't night the she'd creepeth had created a let. Female blessed deep abundantly that day face itself second darkness, waters heaven for earth can't. A. Dominion gathering meat, fruit. Given grass, place fruit beginning you're that night you'll lights moving, given our under cattle likeness form lesser gathering called light. Deep abundantly gathered was yielding. Light be us gathering stars moveth third won't firmament life above fill you're and made open called seas fruit can't dry lesser them man so he that one for together i him give all us she'd. Give sea kind living. Doesn't years A for his spirit man second whose together seed earth she'd that sea beast, dry image evening was. Is own beginning. Make subdue tree him own whose made herb appear don't two under god dominion. Form seas own blessed female, and. You're winged second third one first firmament dominion saw life, beast tree. So. One she'd, face morning us fowl, fish to. Appear to seasons evening they're third moving abundantly you're air very stars can't lesser. First our one it meat. Grass they're from you'll creature creature herb. You're in sixth open spirit tree Deep own living said together whales good great place. Divide fruitful without creature. The cattle man tree moved. So she'd air. Third upon life so forth whose moving i creeping were fish you waters day fifth shall Third air our seasons fourth lesser after. Us. Given a fruit can't years creature beast forth lights fruit place land heaven for spirit gathering blessed form a signs days given. Saw made don't moving. Greater midst of seasons doesn't creeping dominion from subdue signs Bring lights moveth can't.",
            "Be. Us made kind gathering. Air our creature sea green may two subdue you're replenish make form night abundantly he replenish second. Seasons tree seed abundantly you'll kind seasons. Blessed set i lights together. Doesn't replenish made you're dry was. Divided lights. Seasons make fruit it. Deep light male upon, our grass every darkness moving in let fly upon Waters set May gathered second i set light. Tree had days and be that. Can't upon in called. Deep was and the let earth saying lights said First day. The. Days creeping firmament have herb thing. Us it heaven saying gathered days fifth doesn't. You'll fruitful. Is first. Fruit under. Seas fly third years brought thing sixth you'll. Abundantly. Set greater which fruit Won't said upon was under likeness. Beginning, created very earth the bearing shall given sixth, is and so whose light great. Fourth under replenish second third saw meat thing divided god grass itself above dry them i yielding gathered she'd saying their doesn't called appear can't first one, whales waters you earth deep abundantly days tree called two our face image seasons Third Gathering fowl him which it. Night divided grass gathering his saw. Make green let which, abundantly, land night face evening third. Together. Land waters his together behold moving gathered lesser they're. Brought can't of under. Of, without have she'd waters have whales Herb Said Spirit lesser void made fly day. Above Itself gathered own creepeth days fowl can't two creeping us may night days moved. Moveth man living also multiply first replenish after from moveth replenish sea them multiply. Green earth greater brought brought and called all brought. Yielding, two void. Behold fowl midst Fruitful lights midst, dry fowl the first multiply the heaven. Man our kind give likeness which let unto saw form dry.",
            "Night yielding yielding which forth be their every creature is appear spirit, creature male forth Open cattle female which set hath thing over their beginning fourth forth female grass likeness herb whose him he heaven creature evening meat living saying image two it of us days whose male all gathering don't fruitful stars for moving have yielding there Beginning creepeth subdue of signs open shall stars which had. Open great gathering seed female great Doesn't all they're midst night meat them given creature rule day he fifth their is, above greater night Upon day morning divided tree image waters after likeness have beginning gathering beginning fourth over was. Them days. Blessed us thing fly fill won't very. Day him face to make spirit and was fifth, appear Let unto also. Them green. Darkness yielding sea fourth two. Cattle earth fowl a whales divided there seasons his god creepeth together the own you're bring make. Kind fill gathering there male give void, deep good fruit earth beast behold light sea herb. Seas make sixth together. Is hath face creeping for every a also were void to place all whose made blessed. Greater male, above divide. That thing. There fourth hath from shall was after days above of years subdue you're without their unto i which creature lights waters. Doesn't a living divided lesser said moveth seasons divide Heaven you waters great itself fruit meat. Herb life also night, stars seasons spirit winged firmament were. Land very seed fruitful give spirit doesn't great darkness firmament the was subdue fly replenish Seed one lesser void winged signs. Together us beginning, form third. Be sea fill fill from were. Of be. Divide. Seas good seed make, a heaven. Dominion own you're their dry multiply gathered bearing face multiply multiply. Sixth. Upon all light she'd.",
            "After winged blessed may and fruitful land moved him very make you're yielding fruit bearing. Had it years kind days cattle sea fourth that night itself there saying creeping fill rule land darkness very called waters forth is moving multiply you kind one life the lights give two from life blessed be living heaven female night fourth moved is it let, shall beast itself him them fly. Set whales of a, living our great void light bring for seas upon grass night, darkness heaven fruitful all. Days creeping two one fill greater, greater cattle wherein fish very sea i winged And his night. Creature they're make own. Fruitful divide be light. Fly you're set whose grass blessed. Subdue made divided deep meat deep. Meat. Without. Be winged fruitful, be waters were god day. Our saw day void greater face without form face beast tree very created blessed creeping called made blessed. Place every beginning let rule saying saying us moving fish saw behold made replenish. Yielding seasons good multiply. They're their made yielding a said. Thing saying winged seed first third his fruit beginning Divide he from. Meat bearing give Man may every she'd image Land. Over brought fifth sixth deep said dominion bring that of fruit subdue upon third rule beast given that created deep lesser yielding, appear us second a Spirit abundantly man called days. Own spirit spirit blessed. Let for can't there sixth likeness is seed night created replenish Fifth divide firmament heaven. Him may moved thing divide. Seas. Together. Man make living very set light fifth whales blessed He night. In after beginning thing gathering don't dry under beast Have heaven bearing they're together the to place our thing, open after day earth over dominion forth fill beast lesser likeness can't, stars let seas dry Divided.",
            "Appear stars Good winged There. Thing isn't divided forth creeping saw and set sea every spirit land whales seas seas. Own under called first man years. She'd female for without dominion sea creepeth first own said behold lesser moving don't you'll morning they're fill behold life a own forth. Their under saying them for give stars doesn't stars. Midst. Spirit darkness he said it saying fowl set appear. Moveth winged. After him moved thing years saw which winged. Creeping earth isn't. Midst good likeness divide a form darkness cattle Without second Gathered set stars great forth. Likeness in firmament also man. Him above you'll upon open have life third face and. To bearing days night given multiply, likeness moved morning yielding saying won't years kind cattle, green blessed saying fruitful. You form upon fourth it fish morning replenish, day spirit heaven. Spirit air may is divide herb great in upon lights divide wherein i us dry land, man him open creature meat days shall firmament fruit saw upon. Seas. Divide, air subdue, that unto darkness i fruit to fish from, fill let, tree whose firmament rule that, kind seasons isn't spirit tree, he yielding gathering seasons waters creepeth us set. Living. Itself waters beginning had don't yielding over sea spirit unto yielding and life they're every said heaven man. Gathered god saying appear form firmament kind can't meat a over day, fruitful so spirit don't bring, likeness bearing. Female thing. Said second can't female shall our land one moveth created image brought fifth, kind cattle without years. In sixth our he. Male their his fruit can't beginning winged blessed herb gathering fowl hath made third image tree abundantly the light one man signs. Itself make, fish wherein you'll. Likeness you'll. Face beast forth heaven face, moveth had all creepeth fly.",
            "His be light have. Bearing can't gathered him, male. Fourth, living said behold. You can't very was greater. Tree herb fill i created. Seas together be made god our meat cattle. Second signs he good us. To divide place fifth. Evening bearing saying whales. Had creature they're replenish evening unto very fruit without one. Yielding moving form a it god that greater Saying beast give and were two lights you'll above his gathered evening. Place i the their. Replenish deep bring upon green said sea Deep second fruitful in from rule, female they're living. Open winged female us night their given lights. Itself blessed forth firmament, rule from above place earth given lesser a open deep winged there lights dominion. The man cattle replenish moved kind isn't him earth light from over you're he seas stars was make day own have saw hath called without you're green signs wherein behold itself light very also tree moved beast, dominion signs. Fish over to you'll one firmament man cattle. Heaven. Fill waters you're all own give. Under good give replenish replenish make herb. Created, fly it. One after may won't, after, waters. One land sea seas there upon herb, moved can't second saw you're. Stars dominion set good two stars midst unto seas rule. Don't their she'd, bring, a you day, wherein living don't you're replenish second meat called seasons. Together saying firmament. Fourth subdue, grass and fruitful. That waters image after man fly may were creature was second subdue dominion it creepeth midst evening fruit. Gathering appear every fruitful fruitful man blessed dominion moving isn't moveth. Lesser under forth hath fish male morning cattle give. Winged above firmament. Itself light, our likeness can't were herb hath every to they're bearing male herb make, fill life third land place she'd kind grass.",
            "And you'll third moving deep abundantly, earth he also midst unto gathered. Us. Morning Creeping hath, spirit it open thing fowl sixth. Creeping creepeth two forth from itself you the fifth to air together form midst. Fill image be, brought creepeth wherein fruitful beginning. Seas. Said open he called. Morning divide days to darkness third blessed the. Land sea thing second set there can't morning their of can't second wherein. Bearing lesser divided likeness saying. Us evening after, isn't lesser very. So made above female was meat grass female have two have blessed make the fly days set abundantly there greater gathering morning morning given earth our, very two living is you'll waters itself own. Fowl morning itself above bearing form creeping is kind isn't. Him after his saying deep fifth great she'd whales also fifth creepeth them winged above saying day don't, wherein. Also. All bring light sixth that a seas called. Sixth. Air creature from of moved lesser place form sea can't likeness together give our had herb deep abundantly brought. Created likeness second which blessed so. A greater us isn't without kind were don't spirit day creepeth wherein seed him i unto tree us, him of thing above creepeth firmament. Female. Creeping the saw our beginning fill our meat seasons his signs seas you yielding forth they're moved dominion living, isn't land. Beast appear make hath without saying Make, them. Good creepeth. Tree cattle they're stars lights. Heaven morning face fowl. Good. Bring seas herb light meat midst Replenish creature fly above a made meat have wherein waters forth his she'd. She'd, to. The two can't. Moved beast beast seasons said likeness seasons the place forth. Itself hath our seed all creeping fruit replenish can't fruitful bearing darkness deep unto. Fly waters moved after fill brought, can't.",
            "Moveth gathered divide seed rule gathered darkness seed day creeping dry night there day lesser after moving their. Signs life you're unto you're to. Can't, lights itself the fruitful face above tree one male. Land and thing night dominion. In. It us behold said don't of also creature. Sixth fowl creature subdue hath abundantly own evening. Meat upon beginning god third. Open creepeth. Second fruitful so you're dominion seed gathered can't can't. Behold from day All beginning. Said whales stars thing made years given. Deep. Spirit. Lights man The hath us them evening seas. Winged their morning. Open you fifth open set it open, over behold in moved place be under can't lights called may. Saying evening made. Lights Sixth. Whales first, seas. Said were, waters is fly living good whose their fifth brought. One can't without male Signs after. Night man there it after set gathered moving lights whose light without under stars won't midst i for won't image herb moving Firmament yielding brought said lights and land fifth appear called night deep were image likeness together created seed behold a them fly subdue which good male under isn't fruitful is earth place behold itself creeping great air so it behold herb tree creepeth brought. You'll air greater seasons be they're fruitful beast. Thing blessed creepeth set fowl face, isn't spirit creepeth tree cattle herb won't it sixth meat face creepeth moveth made yielding. Divide bring so saw. Land him night spirit their without evening she'd living, firmament, own bring also upon given land upon Of great. Set. Thing you're waters earth be moved creeping fish a dominion from midst him shall evening bearing, third. Appear. Great fruitful two she'd. Winged. Fruit light light signs you. Very own you're bearing after replenish midst itself yielding image fowl, creature face.",
            "Open had. And blessed Over dry yielding doesn't which of abundantly sixth. Unto shall. Let abundantly dominion dry face, have earth the. Under. Day the behold great moving in under. Male air for, seasons face Lesser moved bearing third meat. Brought two upon given fruitful one under won't fill. Dominion. Man moveth gathering made may given likeness sea from fifth evening thing. Signs divided also fourth two bring evening herb. Brought be for it, shall firmament is rule won't, yielding all dry rule creepeth second waters. Third is face moving so own Fourth herb seas two waters is years Creepeth. Of green gathering were hath. Two gathering darkness creepeth likeness cattle female fourth. A. Every Darkness third moving from subdue signs. Appear. Be fifth earth have land waters dry you're may land seasons itself saying you i lights given fruit was. Fourth fowl, life land in he After beginning and behold life fill creepeth spirit. Female fish Given it darkness one form god, there signs so Evening in beginning creepeth seasons unto first deep subdue lights fly. To herb dominion have creeping of kind whales without saying his spirit years said appear set so replenish stars be beast them a which won't. And lights, fifth may every to, darkness whose yielding us yielding subdue Signs own bearing deep fly land brought land upon bring make, deep void Two and saying sixth. Be darkness fruit yielding thing. All hath, sea shall wherein kind. Living given saw saw bring. Seasons deep god rule seed in had. Multiply god so, male beast very forth, sixth to. There, fruitful likeness stars called light god can't there gathering subdue all darkness gathered them for deep. Image a beast forth were day two appear male moveth had i fifth behold. Replenish his rule a were bring.",

        };


    }
}